### ISSUE TITLE
Can't download 1.3 one-jar file.

### ISSUE THREAD

**Issue by ghost** [fgp/AirReceiver#4]
Recently I tried to download a 1.3 one-jar file, which I couldn't do. It seems that file is not found.

**Comment by mvmn** [comment]
Downloaded it today without any problems
https://github.com/fgp/AirReceiver/tree/STABLE_1_X/bin

Great stuff BTW, thanks a lot to the author

**Comment by ghost** [comment]
Mm... still not working for me.

http://gyazo.com/434ddc65c35139df76723f3cd5bdc268

**Comment by mvmn** [comment]
Please try link I've posted (i.e. branch STABLE_1_X) - it seems to have different list of files:
http://i47.tinypic.com/35li88w.png

**Comment by mvmn** [comment]
P.S. Notice it's in /bin folder of branch STABLE_1_X, not in "downloads".

**Comment by ghost** [comment]
Got it, it works for me! Thanks :)
